# -*- coding: utf-8 -*-
"""summer-products_Cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ug26_JX5WVkjux5T_SLAqTX7Yt0OOwk

# Cleaning
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
df = pd.read_csv("/content/summer-products-with-rating-and-performance_2020-08.csv")
df

df.info()

single_value_columns = df.columns[df.nunique() == 1]
single_value_columns

df.drop(columns=["currency_buyer","theme","crawl_month","merchant_profile_picture","urgency_text"],inplace=True)

df["has_urgency_banner"] = df["has_urgency_banner"].fillna(0)

df.isnull().sum()

df.describe()

df["rating_five_count"] = df["rating_five_count"] . fillna(df["rating_five_count"].median())

df["rating_four_count"] = df["rating_four_count"] . fillna(df["rating_four_count"].median())

df["rating_three_count"] = df["rating_three_count"] . fillna(df["rating_three_count"].median())

df["rating_two_count"] = df["rating_two_count"] . fillna(df["rating_two_count"].median())

df["rating_one_count"] = df["rating_one_count"] . fillna(df["rating_one_count"].median())

df["product_color"] = df["product_color"] . fillna(df["product_color"].mode()[0])

df["product_variation_size_id"] = df["product_variation_size_id"].replace({
    "1 pc.": "1pc",
    "04-3XL": "4-3XL",
    "L.": "L",
    "SizeL": "L",
    "M.": "M",
    "s": "S",
    "S.": "S",
    "S..": "S",
    "Size S": "S",
    "size S": "S",
    "Size S.": "S",
    "Size-S": "S",
    "Size/S": "S",
    "SIZE XS": "XS",
    "Size-XS": "XS",
    "XS.": "XS",
    "SIZE XXS": "XXS",
    "size XXS": "XXS",
    "SIZE-XXS": "XXS",
    "Size-XXS": "XXS",
    "SIZE-4X": "4X",
    "Size-5X": "5X",
    "X L": "XL",
    "XXL": "2XL",
    "XXXL": "3XL",
    "XXXXL": "4XL",
    "XXXXXL": "5XL",
    "XXS": "2XS",
    "XXXS": "3XS",
    "SIZEXXS" : "2XS",
    "SIZEL" : "L",
    "SIZES" : "S",
    "SIZE5XL" : "XL",
    "XXS" : "2XS",
    "SIZE4XL" : "4XL",
    "43XL" : "4-3XL"
})

df["product_variation_size_id"] = df["product_variation_size_id"].str.strip().str.upper()

df["product_variation_size_id"] = df["product_variation_size_id"].str.replace(r"[^\w\d]", "", regex=True)

print(df["product_variation_size_id"].unique())

df["product_variation_size_id"] = df["product_variation_size_id"] . fillna(df["product_variation_size_id"].mode()[0])

df["origin_country"] = df["origin_country"] . fillna(df["origin_country"].mode()[0])

df["merchant_name"] = df["merchant_name"].astype(str)
def is_english(text):
    if not isinstance(text, str):
        return False
    return bool(re.match("^[a-zA-Z0-9\s\.,'&\-]+$", text))
df["merchant_name_clean"] = df["merchant_name"].apply(lambda x: x if is_english(x) else None)

df["merchant_name_clean"] = df["merchant_name_clean"] . fillna(df["merchant_name_clean"].mode()[0])

df.dtypes

df.drop(columns=["merchant_name"],inplace=True)

import unicodedata
def normalize_text(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u00A0", " ").replace("\u200f", "")\
               .replace("\u200e", "")
    text = "".join(c for c in text if unicodedata.category(c)[0] != "C")
    return text.strip()

def is_english(text):
    if pd.isna(text):
        return False
    text = normalize_text(text)
    if not text:
        return False
    return bool(re.fullmatch(r"[A-Za-z0-9\s\.,'&\-\(\)%]+", text))

df["merchant_info_subtitle_clean"] = df["merchant_info_subtitle"].apply(
    lambda x: x if is_english(x) else None
)

"""df["merchant_info_subtitle"] = df["merchant_info_subtitle"].astype(str)
def is_english(text):
    if not isinstance(text, str):
        return False
    return bool(re.match("^[a-zA-Z0-9\s\.,'&\-]+$", text))
df["merchant_info_subtitle_clean"] = df["merchant_info_subtitle"].apply(lambda x: x if is_english(x) else None)
"""

df.drop(columns=["merchant_info_subtitle"],inplace=True)

df["merchant_info_subtitle_clean"] = df["merchant_info_subtitle_clean"] . fillna(df["merchant_info_subtitle_clean"].mode()[0])

df.isnull().sum()

"""mode_series = df["merchant_info_subtitle_clean"].mode()
if not mode_series.empty:
    df["merchant_info_subtitle_clean"].fillna(mode_series[0], inplace=True)
"""

df["shipping_option_name"] = df["shipping_option_name"].astype(str)
def is_english(text):
    if not isinstance(text, str):
        return False
    return bool(re.match("^[a-zA-Z0-9\s\.,'&\-]+$", text))
df["shipping_option_name_clean"] = df["shipping_option_name"].apply(lambda x: x if is_english(x) else None)

df.drop(columns=["shipping_option_name"],inplace=True)

df["shipping_option_name_clean"] = df["shipping_option_name_clean"] . fillna(df["shipping_option_name_clean"].mode()[0])

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df.dtypes

df.isnull().sum()

for col in df.select_dtypes(include=['object']).columns:
    try:
        df[col].astype(float)
    except ValueError:
        print(f"⚠ العمود '{col}' يحتوي على قيم غير رقمية أو Errors")
if df.isnull().values.any():
    print("\n✅ يوجد قيم فارغة أو Errors في البيانات")
else:
    print("\n🚀 البيانات سليمة ولا تحتوي على قيم فارغة")

"""# Bussines Question

📌 1- ما هي أكثر الألوان مبيعًا للمنتجات؟
"""

df.groupby("product_color")["units_sold"].sum().sort_values(ascending=False).head(5)

"""📌 2- هل المنتجات التي تحتوي على إعلان مدفوع (uses_ad_boosts) تحقق مبيعات أعلى من غيرها؟"""

df.groupby("uses_ad_boosts")["units_sold"].mean()

"""📌 3- ما هي الدولة الأكثر استهلاك للمنتجات؟"""

df.groupby("origin_country")["units_sold"].sum().sort_values(ascending=False).head(1)

"""📌 4- هل تقييم العميل (merchant_rating) له علاقة بعدد المبيعات؟"""

df.groupby("merchant_rating")["units_sold"].mean()

"""📌 5- ما هي أحجام المنتجات (product_variation_size_id) الأكثر مبيعًا؟"""

df.groupby("product_variation_size_id")["units_sold"].sum().sort_values(ascending=False).head(5)

"""📌 6- هل المنتجات التي لديها شحن سريع (badge_fast_shipping) تحقق مبيعات أكثر؟"""

df.groupby("badge_fast_shipping")["units_sold"].mean()

"""📌 7- ما هو متوسط السعر الحقيقي مقارنة بالسعر المعروض (retail_price vs price)؟"""

df["discount"] = df["retail_price"] - df["price"]
df["discount"].mean()

"""# Visuals

📌 "ما هو توزيع أسعار المنتجات؟"
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['price'], bins=50, kde=True)
plt.title('Price Distribution')
plt.xlabel('Price')
plt.ylabel('Count')
plt.show()

"""📌 "ما هي العلاقة بين السعر المعروض (Retail Price) والسعر الفعلي للبيع (Selling Price)؟"
"""

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='retail_price', y='price', alpha=0.5)
plt.title('Price vs Retail Price')
plt.xlabel('Retail Price')
plt.ylabel('Selling Price')
plt.show()

"""📌 "ما هو توزيع عدد الوحدات المباعة للمنتجات؟"
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['units_sold'], bins=50, kde=True)
plt.title('Units Sold Distribution')
plt.xlabel('Units Sold')
plt.ylabel('Count')
plt.show()

"""📌 "ما هو توزيع تقييمات العملاء (Ratings) للمنتجات؟"
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['rating'], bins=10, kde=True)
plt.title('Rating Distribution')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

"""📌 "ما هو توزيع إجمالي التقييمات حسب عدد النجوم (من 1 إلى 5)؟"
"""

rating_cols = ['rating_five_count', 'rating_four_count', 'rating_three_count', 'rating_two_count', 'rating_one_count']
rating_counts = df[rating_cols].sum().sort_index(ascending=False)

plt.figure(figsize=(8, 5))
sns.barplot(x=rating_counts.index, y=rating_counts.values)
plt.title('Total Ratings by Stars')
plt.xlabel('Rating Stars')
plt.ylabel('Total Count')
plt.show()

"""📌 "ما هو عدد المنتجات التي يتوفر لها شحن سريع (Express Shipping) مقارنة بالمنتجات التي لا يتوفر لها شحن سريع؟"
"""

plt.figure(figsize=(6, 4))
sns.countplot(x='shipping_is_express', data=df)
plt.title('Is Express Shipping?')
plt.xlabel('Express Shipping (0 = No, 1 = Yes)')
plt.ylabel('Number of Products')
plt.show()

"""📌 "ما هو توزيع عدد الدول التي يتم شحن المنتجات إليها؟"
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['countries_shipped_to'], bins=30, kde=True)
plt.title('Countries Shipped To Distribution')
plt.xlabel('Number of Countries')
plt.ylabel('Product Count')
plt.show()

"""📌 " (مميزات خاصة)ما هو عدد المنتجات حسب عدد الشارات (Badges) التي تمتلكها؟"
"""

plt.figure(figsize=(6, 4))
sns.countplot(x='badges_count', data=df)
plt.title('Badges Count')
plt.xlabel('Number of Badges')
plt.ylabel('Product Count')
plt.show()

"""📌 "ما هو توزيع تقييمات التجار (Merchant Rating)؟"
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['merchant_rating'], bins=20, kde=True)
plt.title('Merchant Rating Distribution')
plt.xlabel('Merchant Rating')
plt.ylabel('Count')
plt.show()

"""📌 "ما العلاقة بين عدد التقييمات التي حصل عليها التاجر (Rating Count) ومتوسط تقييمه (Merchant Rating)؟"
"""

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='merchant_rating_count', y='merchant_rating', alpha=0.5)
plt.title('Merchant Rating vs Rating Count')
plt.xlabel('Rating Count')
plt.ylabel('Rating')
plt.show()

"""📌 "ما هو توزيع الشارات (Badges) بين المنتجات؟"
"""

badges = ['badge_local_product', 'badge_product_quality', 'badge_fast_shipping']
badge_sums = df[badges].sum()
plt.figure(figsize=(6, 6))
plt.pie(badge_sums, labels=badge_sums.index, autopct='%1.1f%%', startangle=140)
plt.title('Badge Distribution')
plt.axis('equal')
plt.show()

"""📌 "ما هو توزيع طرق الشحن بين المنتجات (شحن عادي مقابل شحن سريع)؟"
"""

shipping_counts = df['shipping_is_express'].value_counts()
labels = ['Standard Shipping (0)', 'Express Shipping (1)']
plt.figure(figsize=(6, 6))
plt.pie(shipping_counts, labels=labels, autopct='%1.1f%%', startangle=90)
plt.title('Shipping Method Distribution')
plt.axis('equal')
plt.show()

df.to_csv("SUMMER-products-Cleaned.csv", index=False)